# -*- mode: python ; coding: utf-8 -*-

import os

# Obtener dependencias de requirements.txt
def get_hidden_imports():
    hidden_imports = []
    try:
        with open('requirements.txt', 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    # Extraer nombre del paquete (antes de == o >=)
                    package_name = line.split('==')[0].split('>=')[0].split('<=')[0].strip()
                    hidden_imports.append(package_name)
    except:
        pass
    return hidden_imports

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.json', '.'),
        ('.env', '.'),
        ('kia.ico', '.'),
        ('requirements.txt', '.'),
        ('credentials/credentials.json', 'credentials/'),
        ('resources/render_kfn.ahk', 'resources/'),
        ('resources/resources.zip', 'resources/'),
        ('procesos', 'procesos'),
        ('ms_procesos', 'ms_procesos'),
    ],
    hiddenimports=get_hidden_imports() + [
        'tkinter',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'procesos',
        'procesos.management',
        'procesos.management.commands',
        'procesos.management.commands.process_listener',
        'procesos.utils',
        'procesos.utils.path_validator',
        'procesos.utils.logs',
        'procesos.utils.print',
        'procesos.utils.ffmpeg_installer',
        'procesos.services',
        'procesos.services.maquina_info_service',
        'procesos.services.proceso_factory',
        'procesos.repositories',
        'procesos.repositories.cancion_repository',
        'procesos.repositories.proceso_repository',
        'procesos.models',
        'ms_procesos.config',
        'concurrent.futures',
        'psycopg',
        'psycopg_binary',
        'torch',
        'torchaudio',
        'torchvision',
        'demucs',
        'openunmix',
        'julius',
        'lameenc',
        'einops',
        'treetable',
        'submitit',
        'dora_search',
        'cloudpickle',
        'omegaconf',
        'sympy',
        'mpmath',
        'networkx',
        'tqdm',
        'retrying',
        'pystray',
        'pywin32_ctypes',
        'yt_dlp',
        'waitress',
        'colorama',
        'filelock',
        'fsspec',
        'google.auth',
        'google.oauth2',
        'googleapiclient',
        'googleapiclient.discovery',
        'googleapiclient.errors',
        'googleapiclient.http',
        'google_auth_oauthlib',
        'google_auth_oauthlib.flow',
        'requests_oauthlib',
        'oauthlib',
        'urllib3',
        'certifi',
        'idna',
        'charset_normalizer',
        'requests',
        'httplib2',
        'pyasn1',
        'pyasn1_modules',
        'rsa',
        'six',
        'proto_plus',
        'protobuf',
        'google.api_core',
        'googleapis_common_protos',
        'uritemplate',
        'packaging',
        'setuptools',
        'wheel',
        'pip',
        'pkg_resources',
        'distutils',
        'distutils.util',
        'distutils.cmd',
        'distutils.command',
        'distutils.core',
        'distutils.dir_util',
        'distutils.file_util',
        'distutils.spawn',
        'distutils.sysconfig',
        'distutils.version',
        'distutils.command.build_ext',
        'distutils.command.build_py',
        'distutils.command.clean',
        'distutils.command.config',
        'distutils.command.install',
        'distutils.command.install_data',
        'distutils.command.install_headers',
        'distutils.command.install_lib',
        'distutils.command.install_scripts',
        'distutils.command.sdist',
        'Cython',
        'numpy',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'PIL.ImageTk',
        'psutil',
        'pymongo',
        'bson',
        'gridfs',
        'pymongo.errors',
        'pymongo.collection',
        'pymongo.database',
        'pymongo.cursor',
        'pymongo.command_cursor',
        'pymongo.bulk',
        'pymongo.client_session',
        'pymongo.change_stream',
        'pymongo.collation',
        'pymongo.read_preferences',
        'pymongo.read_concern',
        'pymongo.write_concern',
        'pymongo.operations',
        'pymongo.pool',
        'pymongo.son_manipulator',
        'pymongo.topology',
        'pymongo.topology_description',
        'pymongo.server_description',
        'pymongo.monitor',
        'pymongo.monitoring',
        'pymongo.periodic_executor',
        'pymongo.server',
        'pymongo.server_type',
        'pymongo.socket_info',
        'pymongo.ssl_support',
        'pymongo.uri_parser',
        'pymongo.auth',
        'pymongo.helpers',
        'pymongo.message',
        'pymongo.response',
        'pymongo.codec',
        'pymongo.codec_options',
        'pymongo.driver_info',
        'pymongo.encryption',
        'pymongo.encryption_options',
        'pymongo.hello',
        'pymongo.ismaster',
        'pymongo.network',
        'pymongo.results',
        'pymongo.saslprep',
        'pymongo.server_api',
        'pymongo.server_selectors',
        'pymongo.session',
        'pymongo.settings',
        'pymongo.thread_util',
        'pymongo.timestamp',
        'pymongo.tz_util',
        'pymongo.write_buffer',
        'pymongo.errors',
        'pymongo.common',
        'pymongo.typeddict',
        'pymongo.typings',
        'pymongo.validation',
        'pymongo.version',
        'pymongo.compat',
        'pymongo.daemon',
        'pymongo.event_loggers',
        'pymongo.logger',
        'pymongo.lock',
        'pymongo.lock_file',
        'pymongo.max_staleness_selectors',
        'pymongo.min_key',
        'pymongo.max_key',
        'pymongo.objectid',
        'pymongo.regex',
        'pymongo.binary',
        'pymongo.code',
        'pymongo.dbref',
        'pymongo.json_util',
        'pymongo.int64',
        'pymongo.decimal128',
        'pymongo.uuid',
        'pymongo.datetime_ms',
        'pymongo.errors',
        'pymongo.errors.BulkWriteError',
        'pymongo.errors.ConfigurationError',
        'pymongo.errors.ConnectionFailure',
        'pymongo.errors.CursorNotFound',
        'pymongo.errors.DocumentTooLarge',
        'pymongo.errors.DuplicateKeyError',
        'pymongo.errors.EncryptionError',
        'pymongo.errors.ExecutionTimeout',
        'pymongo.errors.InvalidDocument',
        'pymongo.errors.InvalidName',
        'pymongo.errors.InvalidOperation',
        'pymongo.errors.NetworkTimeout',
        'pymongo.errors.NotMasterError',
        'pymongo.errors.OperationFailure',
        'pymongo.errors.ProtocolError',
        'pymongo.errors.PyMongoError',
        'pymongo.errors.ServerSelectionTimeoutError',
        'pymongo.errors.WriteError',
        'pymongo.errors.WriteConcernError',
        'pymongo.errors.WTimeoutError',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Ms_Procesos',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='kia.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='MsProcesos',
)
